import global from 'global';

const Components = global.__STORYBOOKCOMPONENTS__;

export const {
    A,
    ActionBar,
    AddonPanel,
    Badge,
    Bar,
    Blockquote,
    Button,
    Code,
    DL,
    Div,
    DocumentWrapper,
    FlexBar,
    Form,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HR,
    IconButton,
    IconButtonSkeleton,
    Icons,
    Img,
    LI,
    Link,
    Loader,
    OL,
    P,
    Placeholder,
    Pre,
    ResetWrapper,
    ScrollArea,
    Separator,
    Spaced,
    Span,
    StorybookIcon,
    StorybookLogo,
    Symbols,
    SyntaxHighlighter,
    TT,
    TabBar,
    TabButton,
    TabWrapper,
    Table,
    Tabs,
    TabsState,
    TooltipLinkList,
    TooltipMessage,
    TooltipNote,
    UL,
    WithTooltip,
    WithTooltipPure,
    Zoom,
    codeCommon,
    components,
    createCopyToClipboardFunction,
    getStoryHref,
    interleaveSeparators,
    nameSpaceClassNames,
    resetComponents,
    withReset,
} = Components;
export default Components;
